<?php
// $Id: xoops_version.php,v 1.2 2007/11/12 12:28:48 ohwada Exp $

// 2007-11-01 K.OHWADA
// hasAdmin

// 2006-07-10 K.OHWADA
// this is new file

//=========================================================
// Happy Linux Framework Module
// 2006-07-10 K.OHWADA
//=========================================================

$moduleDirName      = basename(__DIR__);
$moduleDirNameUpper = mb_strtoupper($moduleDirName);

//require_once XOOPS_ROOT_PATH . '/modules/happylinux/include/version.php';

//$modversion['name']        = _MI_HAPPYLINUX_NAME;
//$modversion['description'] = _MI_HAPPYLINUX_DESC;
//$modversion['version']     = HAPPYLINUX_VERSION;

$modversion['version']             = '2.00';
$modversion['release_date']        = '2020/03/11';
$modversion['module_status']       = 'Alpha 1';
$modversion['name']                = _MI_HAPPYLINUX_NAME;
$modversion['description']         = _MI_HAPPYLINUX_DESC;
$modversion['author']              = 'Kenichi OHWADA<br>( https://linux2.ohwada.net/ )';
$modversion['credits']             = '';
$modversion['help']                = '';
$modversion['license']             = 'GPL see LICENSE';
$modversion['official']            = 0;
$modversion['dirname']             = $moduleDirName;
$modversion['modicons16']          = 'assets/images/icons/16';
$modversion['modicons32']          = 'assets/images/icons/32';
$modversion['image']               = 'assets/images/logoModule.png';
$modversion['module_website_url']  = 'https://xoops.org';
$modversion['module_website_name'] = 'XOOPS';
$modversion['min_php']             = '5.6';
$modversion['min_xoops']           = '2.5.10';
$modversion['min_admin']           = '1.2';
$modversion['min_db']              = ['mysql' => '5.5'];
$modversion['system_menu']         = 1;
$modversion['adminindex']          = 'admin/index.php';
$modversion['adminmenu']           = 'admin/menu.php';

// Sql file (must contain sql generated by phpMyAdmin or phpPgAdmin)
// All tables should not have any prefix!
//$modversion['sqlfile']['mysql'] = '';

// Tables created by sql file (without prefix!)
//$modversion['tables'][0] = '';

// Admin things
$modversion['system_menu'] = 1;
$modversion['hasAdmin']    = 1;
$modversion['adminindex']  = 'admin/index.php';
$modversion['adminmenu']   = 'admin/menu.php';

// Menu
$modversion['hasMain'] = 0;
//$modversion['sub'][1]['name'] = '';
//$modversion['sub'][1]['url']  = '';

//  Search
$modversion['hasSearch'] = 0;
//$modversion['search']['file'] = '';
//$modversion['search']['func'] = '';

// Blocks
//$modversion['blocks'][1]['file']        = '';
//$modversion['blocks'][1]['name']        = '';
//$modversion['blocks'][1]['description'] = '';
//$modversion['blocks'][1]['show_func']   = '';
//$modversion['blocks'][1]['edit_func']   = '';
//$modversion['blocks'][1]['options']     = '';
//$modversion['blocks'][1]['template']    = ''';

// Templates
//$modversion['templates'][1]['file'] = '';
//$modversion['templates'][1]['description'] = '';

/**
 * Make Sample button visible?
 */
$modversion['config'][] = [
    'name'        => 'displaySampleButton',
    'title'       => 'CO_' . $moduleDirNameUpper . '_' . 'SHOW_SAMPLE_BUTTON',
    'description' => 'CO_' . $moduleDirNameUpper . '_' . 'SHOW_SAMPLE_BUTTON_DESC',
    'formtype'    => 'yesno',
    'valuetype'   => 'int',
    'default'     => 1,
];

/**
 * Show Developer Tools?
 */
$modversion['config'][] = [
    'name'        => 'displayDeveloperTools',
    'title'       => 'CO_' . $moduleDirNameUpper . '_' . 'SHOW_DEV_TOOLS',
    'description' => 'CO_' . $moduleDirNameUpper . '_' . 'SHOW_DEV_TOOLS_DESC',
    'formtype'    => 'yesno',
    'valuetype'   => 'int',
    'default'     => 0,
];
